ANALYSIS_RAW="analysis_raw"
ANALYSIS_KEY="analysis_result"
QUESTIONS_KEY="questions_generation_result"
ERRORS_KEY="questions_errors"
QUESTION_PLAN="question_plans"
CORRECTION_LIST = "correction_list"
